Add Binary and Hashable instances.
ConferHealth/composite pull request #39
Opened 2020-08-13 17:03 UTC by locallycompact

2020-08-17 18:00 UTC, Dridus requested changes
since you have all the commits stacked, feel free to submit a unified PR for all four issues

2020-08-17 18:00 UTC, Dridus commented on composite-binary-instance/package.yaml
> +name:                composite-binary-instance
can you rename this to `composite-binary` to match the overall naming scheme?

2020-08-17 18:00 UTC, Dridus commented on composite-binary-instance/package.nix
> +  description = "composite-aeson support for Refined from the refined package";
same comment here about using `make` to have this file auto generated

2020-08-17 18:00 UTC, Dridus commented on composite-binary-instance/src/Composite/Record/Binary.hs
> +instance Binary a => Binary (s :-> a) where
`deriving instance Binary a => Binary (s :-> a)` with `GeneralizedNewtypeDeriving` turned on should do the same thing?

2020-08-17 18:00 UTC, Dridus commented on composite-binary-instance/src/Composite/Record/Binary.hs
> +instance (Binary a, Binary (Record xs), x ~ (s :-> a)) => Binary (Record (x : xs)) where
same comment here as for `NFData` - make it more general, e.g. `instance (Binary (f r), Binary (Rec f rs)) => Binary (Rec f (r ': rs))` and also make sure there are no compiler warnings being eaten

2020-08-17 18:00 UTC, Dridus commented on stack.yaml
> +  - composite-binary-instance
and to `stack-8.8.3.yaml`?

2020-08-17 18:00 UTC, Dridus commented on composite-hashable-instance/package.yaml
> +name:                composite-hashable-instance
same request with naming - drop `-instance` please

2020-08-17 18:00 UTC, Dridus commented on composite-hashable-instance/src/Composite/Record/Hashable.hs
> +instance (Hashable a, Hashable (Record xs), x ~ (s :-> a)) => Hashable (Record (x : xs)) where
same comment about generalizing as for `NFData` and `Binary`

2020-08-17 18:57 UTC, locallycompact commented
The whole stack is here, lmk if I missed anything.

2020-08-17 21:58 UTC, Dridus requested changes
`composite-aeson-path/src/Composite/Aeson/Path.hs` is triggering the orphan warning/error, so needs `{-# OPTIONS_GHC -fno-warn-orphans #-}`

2020-08-24 16:27 UTC, locallycompact commented
How's this?

2020-08-25 22:53 UTC, Dridus approved these changes

2020-08-25 22:53 UTC, merged